/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RendersRouteImport } from './routes/renders'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SourcesMarkdownRouteImport } from './routes/sources.markdown'
import { Route as SourcesGithubRouteImport } from './routes/sources.github'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RendersRoute = RendersRouteImport.update({
  id: '/renders',
  path: '/renders',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesMarkdownRoute = SourcesMarkdownRouteImport.update({
  id: '/sources/markdown',
  path: '/sources/markdown',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesGithubRoute = SourcesGithubRouteImport.update({
  id: '/sources/github',
  path: '/sources/github',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/drafts': typeof DraftsRoute
  '/generate': typeof GenerateRoute
  '/inbox': typeof InboxRoute
  '/renders': typeof RendersRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/sources/github': typeof SourcesGithubRoute
  '/sources/markdown': typeof SourcesMarkdownRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/drafts': typeof DraftsRoute
  '/generate': typeof GenerateRoute
  '/inbox': typeof InboxRoute
  '/renders': typeof RendersRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/sources/github': typeof SourcesGithubRoute
  '/sources/markdown': typeof SourcesMarkdownRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/drafts': typeof DraftsRoute
  '/generate': typeof GenerateRoute
  '/inbox': typeof InboxRoute
  '/renders': typeof RendersRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/templates': typeof TemplatesRoute
  '/sources/github': typeof SourcesGithubRoute
  '/sources/markdown': typeof SourcesMarkdownRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/drafts'
    | '/generate'
    | '/inbox'
    | '/renders'
    | '/schedule'
    | '/settings'
    | '/templates'
    | '/sources/github'
    | '/sources/markdown'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/drafts'
    | '/generate'
    | '/inbox'
    | '/renders'
    | '/schedule'
    | '/settings'
    | '/templates'
    | '/sources/github'
    | '/sources/markdown'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/drafts'
    | '/generate'
    | '/inbox'
    | '/renders'
    | '/schedule'
    | '/settings'
    | '/templates'
    | '/sources/github'
    | '/sources/markdown'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DraftsRoute: typeof DraftsRoute
  GenerateRoute: typeof GenerateRoute
  InboxRoute: typeof InboxRoute
  RendersRoute: typeof RendersRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  TemplatesRoute: typeof TemplatesRoute
  SourcesGithubRoute: typeof SourcesGithubRoute
  SourcesMarkdownRoute: typeof SourcesMarkdownRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renders': {
      id: '/renders'
      path: '/renders'
      fullPath: '/renders'
      preLoaderRoute: typeof RendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/markdown': {
      id: '/sources/markdown'
      path: '/sources/markdown'
      fullPath: '/sources/markdown'
      preLoaderRoute: typeof SourcesMarkdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/github': {
      id: '/sources/github'
      path: '/sources/github'
      fullPath: '/sources/github'
      preLoaderRoute: typeof SourcesGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  DraftsRoute: DraftsRoute,
  GenerateRoute: GenerateRoute,
  InboxRoute: InboxRoute,
  RendersRoute: RendersRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  TemplatesRoute: TemplatesRoute,
  SourcesGithubRoute: SourcesGithubRoute,
  SourcesMarkdownRoute: SourcesMarkdownRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
