// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDraft'](arg1, arg2, arg3);
}

export function DeleteDraft(arg1) {
  return window['go']['main']['App']['DeleteDraft'](arg1);
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function ListAIProviders() {
  return window['go']['main']['App']['ListAIProviders']();
}

export function ListDrafts() {
  return window['go']['main']['App']['ListDrafts']();
}

export function RenderTemplate(arg1) {
  return window['go']['main']['App']['RenderTemplate'](arg1);
}
