// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {draft} from '../models';
import {application} from '../models';
import {ai} from '../models';
import {template} from '../models';

export function CreateDraft(arg1:string,arg2:string,arg3:string):Promise<draft.Draft>;

export function DeleteDraft(arg1:string):Promise<void>;

export function GenerateContent(arg1:application.GenerateRequest):Promise<ai.GenerateOutput>;

export function ListAIProviders():Promise<Array<ai.ProviderInfo>>;

export function ListDrafts():Promise<Array<draft.Draft>>;

export function RenderTemplate(arg1:template.RenderRequest):Promise<template.RenderResult>;
