// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AIProviders() {
  return window['go']['main']['App']['AIProviders']();
}

export function CreateDraft(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDraft'](arg1, arg2, arg3);
}

export function DeleteDraft(arg1) {
  return window['go']['main']['App']['DeleteDraft'](arg1);
}

export function ListDrafts() {
  return window['go']['main']['App']['ListDrafts']();
}
